namespace NBC.Asset.Editor
{
    public enum FilterEnum
    {
        //全部
        All = 0, 
        //预制体
        Prefab, 
        //场景
        Scene, 
        //题图
        Texture, 
        //精灵图片
        Sprite, 
        //文件资产
        TextAsset, 
        //材质
        Material, 
        //网格
        Mesh, 
        //字体
        Font, 
        //模型
        Model, 
        //着色器
        Shader, 
        //音频
        AudioClip, 
        //音频混音器
        AudioMixer, 
        //视频
        VideoClip, 
        //动画
        AnimationClip, 
        //物理材质
        PhysicMaterial, 
        //脚本
        Script, 
        //动画控制器
        RuntimeAnimatorController, 
        //自定义
        Custom
    }
}